import os
import sys
import time
import requests
from requests.exceptions import RequestException

# Configurable Timeout & Retry Settings
API_TIMEOUT = 180  # 3 minutes for long-form Hindi post generation
MAX_RETRIES = 3


def generate_blog_content():
    gemini_key = os.getenv("GEMINI_KEY")
    if not gemini_key:
        raise ValueError("❌ GEMINI_KEY environment variable missing!")

    # Gemini 2.5 Flash Endpoint
    url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key={gemini_key}"
    headers = {"Content-Type": "application/json"}

    # Correct REST API Payload Structure
    payload = {
        "contents": [
            {
                "parts": [
                    {
                        "text": "Write a detailed, SEO-optimized blog post in Hindi about Personal Finance & Money Management."
                    }
                ]
            }
        ]
    }

    print("🔍 [DEBUG] Sending request to Gemini 2.5 API...")

    for attempt in range(1, MAX_RETRIES + 1):
        try:
            response = requests.post(
                url, json=payload, headers=headers, timeout=API_TIMEOUT
            )
            response.raise_for_status()

            data = response.json()

            # Safe Parsing of API Response
            candidates = data.get("candidates", [])
            if not candidates:
                raise ValueError(f"No content generated by API: {data}")

            generated_text = candidates[0]["content"]["parts"][0]["text"]

            title = "Finance & Personal Money Management"
            body_html = generated_text
            category_used = "Finance"

            return title, body_html, category_used

        except RequestException as e:
            print(f"⚠️ [Attempt {attempt}/{MAX_RETRIES}] Request failed: {e}")
            if attempt == MAX_RETRIES:
                print("❌ [ERROR] Max retries reached. Failing process...")
                raise
            sleep_time = 5 * attempt
            print(f"🔄 Retrying in {sleep_time} seconds...")
            time.sleep(sleep_time)


def main():
    print("==========================================")
    print("🔍 [DEBUG] Step 1: Checking Environment Variables...")
    print(f"👉 GEMINI_KEY Present: {bool(os.getenv('GEMINI_KEY'))}")
    print(f"👉 GMAIL_USER: {os.getenv('GMAIL_USER')}")
    print(f"👉 GMAIL_PASS Present: {bool(os.getenv('GMAIL_PASS'))}")
    print(f"👉 BLOGGER_EMAIL: {os.getenv('BLOGGER_EMAIL')}")
    print(f"👉 WA_PHONE: {os.getenv('WA_PHONE')}")
    print(f"👉 TMB_KEY Present: {bool(os.getenv('TMB_KEY'))}")
    print(f"👉 BLOG_LANG: {os.getenv('BLOG_LANG', 'HINDI')}")
    print("==========================================")
    print("🚀 [System] Starting Auto SEO Blog Publisher...")
    print("🤖 [Gemini Engine] Generating High-Ranking SEO Blog Content...")

    try:
        title, body_html, category_used = generate_blog_content()
        print("✅ Content generated successfully!")
        print(f"📌 Generated Title: {title}")
        print(f"📂 Category Used: {category_used}")

    except Exception as e:
        print(f"❌ Execution failed: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
